# Generated by Django 5.2.17 on 2026-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("source", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
