# Generated by Django 5.2.17 on 2026-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="tickers",
            field=models.ManyToManyField(
                blank=True, related_name="news_items", to="scanner.ticker"
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
