# Generated by Django 5.2.17 on 2026-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsitem_tickers_alter_newsitem_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("country", models.CharField(default="USD", max_length=10)),
                ("event_time", models.DateTimeField()),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Baja (1 estrella)"),
                            ("medium", "Media (2 estrellas)"),
                            ("high", "Alta (3 estrellas)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("forecast", models.CharField(blank=True, max_length=40)),
                ("previous", models.CharField(blank=True, max_length=40)),
                ("actual", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["event_time"],
                "unique_together": {("title", "event_time")},
            },
        ),
    ]
