# Generated by Django 5.2.17 on 2026-08-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="Se renderiza como HTML sin sanitizar (safe) — solo para contenido de confianza."
            ),
        ),
    ]
