# Generated by Django 5.2.17 on 2026-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="nombre"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                ("message", models.TextField(verbose_name="mensaje")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False, verbose_name="leído")),
            ],
            options={
                "verbose_name": "sugerencia/comentario",
                "verbose_name_plural": "sugerencias/comentarios",
                "ordering": ["-created_at"],
            },
        ),
    ]
