# Generated by Django 5.2.17 on 2026-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_en",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
