"""
Django settings for config project.



Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de .env (no versionado, ver .env.example) si existe.
# En el servidor de producción, en vez de un .env, normalmente se
# configuran estas mismas variables directamente en el panel del
# hosting — load_dotenv() no falla si el archivo no existe.
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
# El valor de abajo es solo un respaldo para que el sitio arranque en
# un checkout nuevo sin .env configurado — en producción SIEMPRE debe
# venir de la variable de entorno SECRET_KEY (ver .env.example).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-2n_8y@=)00zx9&kfz%f_56nmd!ej&z2%-f1_36)c-^rxn#xa5)',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# dsminds.com es el dominio real del sitio (DSMarketLearning). Se
# mantienen también localhost/127.0.0.1 para seguir probando en local,
# y ALLOWED_HOSTS se puede ampliar sin tocar código con la variable de
# entorno del mismo nombre (lista separada por comas).
ALLOWED_HOSTS = [
    'dsminds.com',
    'www.dsminds.com',
    'localhost',
    '127.0.0.1',
] + [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    'https://dsminds.com',
    'https://www.dsminds.com',
]

# Solo se activan con DEBUG=False (producción real) — con DEBUG=True
# romperían las pruebas locales por HTTP (redirect a HTTPS en loop).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 semana, para no arriesgar un typo en el dominio al principio
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # La mayoría de hostings (Render, Railway, etc.) ponen la app detrás
    # de un proxy que termina el TLS y reenvía por HTTP puro — sin esto,
    # Django no sabría que la conexión original sí era HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scanner',
    'news',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.language',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# `collectstatic` copia todo a STATIC_ROOT; whitenoise sirve desde ahí
# en producción (comprimido, con hash en el nombre para cache-busting
# real, sin necesitar el `?v=...` que se usa en las plantillas para
# desarrollo). En local, `runserver` sigue sirviendo directo desde
# STATICFILES_DIRS sin pasar por collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'scanner': {'handlers': ['console'], 'level': 'INFO'},
        'news': {'handlers': ['console'], 'level': 'INFO'},
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
