# Generated by Django 5.2.17 on 2026-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_scanresult_above_ma200_scanresult_atr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
