# Generated by Django 5.2.17 on 2026-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_scanresult_target_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="debt_to_equity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="market_cap_display",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="peg_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="trailing_pe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
