# Generated by Django 5.2.17 on 2026-08-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_scanresult_debt_to_equity_scanresult_market_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="exchange",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
