# Generated by Django 5.2.17 on 2026-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_scanresult_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticker",
            name="added_manually",
            field=models.BooleanField(default=False),
        ),
    ]
