# Generated by Django 5.2.17 on 2026-08-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_ticker_added_at_ticker_added_manually"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="current_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="macd",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="macd_bullish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="macd_signal",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
