# Generated by Django 5.2.17 on 2026-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0007_scanresult_current_ratio_scanresult_macd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("penny", "Penny"),
                    ("monster", "Monster"),
                    ("standard", "Standard"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="momentum_rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="momentum_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
