# Generated by Django 5.2.17 on 2026-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0008_scanresult_group_scanresult_momentum_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="eps_growth",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="return_3m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="roe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="sharpe_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
