# Generated by Django 5.2.17 on 2026-08-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=80)),
                ("yfinance_symbol", models.CharField(max_length=20)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("index", "Índice"),
                            ("forex", "Forex"),
                            ("commodity", "Materia prima"),
                        ],
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="NewsHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("headline", models.CharField(max_length=300)),
                ("related_symbols", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("country", models.CharField(blank=True, max_length=10)),
                ("title", models.CharField(max_length=200)),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                        ],
                        default="low",
                        max_length=6,
                    ),
                ),
                (
                    "actual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "forecast",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "previous",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time"],
                "unique_together": {("event_time", "title", "country")},
            },
        ),
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("15m", "15 minutos"),
                            ("1h", "1 hora"),
                            ("4h", "4 horas"),
                            ("1d", "Diaria"),
                            ("1w", "Semanal"),
                        ],
                        max_length=3,
                    ),
                ),
                ("version", models.CharField(max_length=40)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("mae", models.DecimalField(decimal_places=6, max_digits=14)),
                ("rmse", models.DecimalField(decimal_places=6, max_digits=14)),
                ("n_samples", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_runs",
                        to="dsprofeta.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("15m", "15 minutos"),
                            ("1h", "1 hora"),
                            ("4h", "4 horas"),
                            ("1d", "Diaria"),
                            ("1w", "Semanal"),
                        ],
                        max_length=3,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("target_time", models.DateTimeField()),
                (
                    "predicted_close",
                    models.DecimalField(decimal_places=5, max_digits=14),
                ),
                ("model_version", models.CharField(max_length=40)),
                (
                    "actual_close",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="dsprofeta.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("15m", "15 minutos"),
                            ("1h", "1 hora"),
                            ("4h", "4 horas"),
                            ("1d", "Diaria"),
                            ("1w", "Semanal"),
                        ],
                        max_length=3,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=5, max_digits=14)),
                ("high", models.DecimalField(decimal_places=5, max_digits=14)),
                ("low", models.DecimalField(decimal_places=5, max_digits=14)),
                ("close", models.DecimalField(decimal_places=5, max_digits=14)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="dsprofeta.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("asset", "timeframe", "timestamp")},
            },
        ),
    ]
