# Generated by Django 5.2.17 on 2026-08-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsprofeta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="model_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
