# Generated by Django 5.2.17 on 2026-09-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsprofeta", "0002_modelrun_model_blob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("index", "Índice"),
                    ("forex", "Forex"),
                    ("commodity", "Materia prima"),
                    ("crypto", "Cripto"),
                ],
                max_length=12,
            ),
        ),
    ]
